sonar.projectKey=Sristi1123_polyglot-sandbox
sonar.organization=Sristi1123
sonar.host.url=https://sonarcloud.io
sonar.token=af3dadecabad93d73742b78f437a2c47c7133733
sonar.sources=src
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
